Server:
  Host: "aller-retour.com"
Logger:
  Path: "/var/log/aller_retour/api.log"
Auth:
  Secret: ""
  Issuer: "https://aller-retour.com"
  Audience: "https://aller-retour.com"
Mail:
  Host: "mail.aller-retour.com"
  Address: "noreply@aller-retour.com"
